### ISSUE TITLE
Mix up in orientation and movement colour

### ISSUE THREAD

**Issue by HenningSte** [younesStrittmatter/rdkOnline#1]
Could it be that there is a mix up somewhere with the colours you are using?
While the task description says the following:
![image](https://github.com/younesStrittmatter/rdkOnline/assets/30557436/6dbc3f85-a5dc-4a48-9470-10da5a4cc284)

For me at least the opposite is actually the case. For a blue cross I have to react to the orientation, for yellow I have to react to the movement. 
Otherwise I get a huge error rate in the training section and completely useless data.

**Comment by younesStrittmatter** [comment]
You are right! I corrected it. Sorry for the mix-up, and thank you a lot for bringing this to our attention.
